// ─── Company & week ───────────────────────────────────────────────────────────
export const demoWeek = {
  period: "Feb 17–21, 2026",
  company: "Aksara HRtech",
  stats: {
    conversations: 47,
    signals: 12,
    critical: 3,
    dealsAtRisk: 6,
  },
}

// ─── Connected integrations ───────────────────────────────────────────────────
export const demoIntegrations = [
  {
    id: "whatsapp",
    name: "WhatsApp Business",
    category: "Conversation",
    description: "Sales & pre-sales conversations",
    status: "connected" as const,
    icon: "💬",
    color: "bg-green-50 border-green-200",
    dot: "bg-green-500",
    stats: { label: "this week", value: "31 conversations" },
    connectUrl: "https://business.whatsapp.com/",
    setupSteps: [
      "Create a WhatsApp Business account",
      "Apply for the Cloud API via Meta Business Suite",
      "Paste your webhook URL and verify token",
      "Assign the Nectic phone number to your sales team",
    ],
  },
  {
    id: "zoom",
    name: "Zoom / Fireflies",
    category: "Conversation",
    description: "Demo calls & discovery recordings",
    status: "connected" as const,
    icon: "🎥",
    color: "bg-blue-50 border-blue-200",
    dot: "bg-blue-500",
    stats: { label: "this week", value: "9 call transcripts" },
    connectUrl: "https://fireflies.ai/",
    setupSteps: [
      "Connect your Fireflies workspace to Nectic",
      "Fireflies auto-joins scheduled Zoom/Meet calls",
      "Transcripts sync within 15 min of call end",
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot CRM",
    category: "CRM",
    description: "Deal notes & contact activity",
    status: "connected" as const,
    icon: "🔶",
    color: "bg-orange-50 border-orange-200",
    dot: "bg-orange-500",
    stats: { label: "this week", value: "7 deal notes" },
    connectUrl: "https://hubspot.com/",
    setupSteps: [
      "Authorise Nectic via HubSpot OAuth",
      "Select which deal pipelines to monitor",
      "Nectic reads notes, emails, and call logs",
    ],
  },
  {
    id: "jira",
    name: "Jira",
    category: "Output",
    description: "Auto-create tickets from signals",
    status: "connected" as const,
    icon: "📋",
    color: "bg-indigo-50 border-indigo-200",
    dot: "bg-indigo-500",
    stats: { label: "this week", value: "3 tickets created" },
    connectUrl: "https://atlassian.com/jira",
    setupSteps: [
      "Authorise Nectic via Atlassian OAuth",
      "Choose default project and issue type",
      "Tickets are created when you click 'Create ticket' on any signal",
    ],
  },
  {
    id: "slack",
    name: "Slack",
    category: "Output",
    description: "Weekly brief delivered to #product",
    status: "connected" as const,
    icon: "📢",
    color: "bg-purple-50 border-purple-200",
    dot: "bg-purple-500",
    stats: { label: "delivery", value: "Mon 8:00 AM" },
    connectUrl: "https://slack.com/",
    setupSteps: [
      "Add Nectic to your Slack workspace",
      "Choose the channel (e.g. #product-intel)",
      "Brief is posted every Monday at 8 AM local time",
    ],
  },
  {
    id: "linear",
    name: "Linear",
    category: "Output",
    description: "Auto-create issues from signals",
    status: "available" as const,
    icon: "⬡",
    color: "bg-neutral-50 border-neutral-200",
    dot: "bg-neutral-300",
    stats: { label: "status", value: "Not connected" },
    connectUrl: "https://linear.app/",
    setupSteps: [],
  },
]

// ─── Raw conversation feed ────────────────────────────────────────────────────
export const demoConversations = [
  {
    id: "c1",
    source: "whatsapp",
    sourceLabel: "WhatsApp",
    sender: "Budi Santoso",
    company: "PT Karya Maju",
    date: "Feb 18, 10:32",
    preview: "Kami suka UI-nya tapi tim finance kami tidak mau input data dua kali...",
    full: "Halo, kami suka UI-nya tapi tim finance kami tidak mau input data dua kali ke dua sistem. Sampai ada integrasi dengan Gadjian, kami belum bisa pindah. Ini hard blocker buat kami.",
    signals: ["payroll-sync-gap"],
    status: "processed" as const,
  },
  {
    id: "c2",
    source: "zoom",
    sourceLabel: "Zoom call",
    sender: "Rina Wijaya",
    company: "Teknologi Hijau",
    date: "Feb 18, 14:00",
    preview: "Transcript: discovery call — 38 min. Key moment at 12:40...",
    full: "[12:40] Rina: Kalau ada konektor Talenta, saya tanda tangan hari ini. Tim kami sudah evaluasi 3 vendor, dan ini satu-satunya yang kurang. [13:05] Sales: Oke noted, saya akan escalate ke tim produk.",
    signals: ["payroll-sync-gap"],
    status: "processed" as const,
  },
  {
    id: "c3",
    source: "whatsapp",
    sourceLabel: "WhatsApp",
    sender: "Agus Pratama",
    company: "Bangun Bersama",
    date: "Feb 17, 09:14",
    preview: "Manajer ops saya approve dari HP tapi selalu komplain kelamaan...",
    full: "Manajer ops saya approve dari HP tapi selalu komplain kelamaan. Akhirnya dia approve semua tanpa dibaca biar cepat selesai. Ini berbahaya untuk kontrol internal kami.",
    signals: ["mobile-approval-friction"],
    status: "processed" as const,
  },
  {
    id: "c4",
    source: "hubspot",
    sourceLabel: "HubSpot note",
    sender: "Sales rep: Dian",
    company: "Logistik Nusantara",
    date: "Feb 19, 16:00",
    preview: "Note: Customer reported mobile app crashes on >5 pending...",
    full: "Call summary: Customer reported mobile app crashes when there are more than 5 pending approval requests. This has been reported 3 times this month. Customer is evaluating Keka as alternative. Risk: HIGH.",
    signals: ["mobile-approval-friction"],
    status: "processed" as const,
  },
  {
    id: "c5",
    source: "whatsapp",
    sourceLabel: "WhatsApp",
    sender: "Sari Dewi",
    company: "Sejahtera Group",
    date: "Feb 18, 11:45",
    preview: "Kami coba upload 200 karyawan dari sistem lama tapi template...",
    full: "Kami coba upload 200 karyawan dari sistem lama tapi template Excel-nya tidak ada instruksi. Akhirnya kami telepon support. Bisa dibuat lebih mudah?",
    signals: ["bulk-import-docs"],
    status: "processed" as const,
  },
  {
    id: "c6",
    source: "zoom",
    sourceLabel: "Zoom call",
    sender: "Hendra Kusuma",
    company: "Mitra Solusi",
    date: "Feb 20, 10:00",
    preview: "Transcript: QBR call — 52 min. Payroll blocker raised at 8:20...",
    full: "[08:20] Hendra: Demo-nya bagus tapi kami perlu bicara dulu sama vendor payroll kami. Ini blocker buat kami. [09:00] Sales: Noted. Kami sedang develop ini untuk Q2. [09:10] Hendra: Q2 terlalu lama, kami butuh keputusan bulan ini.",
    signals: ["payroll-sync-gap"],
    status: "processed" as const,
  },
  {
    id: "c7",
    source: "whatsapp",
    sourceLabel: "WhatsApp",
    sender: "Putri Handayani",
    company: "Aman Logistik",
    date: "Feb 19, 14:22",
    preview: "Saya harus export laporan 4 kali untuk dapat data satu tahun...",
    full: "Saya harus export laporan 4 kali untuk dapat data satu tahun penuh. Bisa langsung pilih range tanggal sendiri? Tim audit kami minta data 12 bulan tapi sistemnya cuma bisa 90 hari.",
    signals: ["report-date-range"],
    status: "processed" as const,
  },
  {
    id: "c8",
    source: "hubspot",
    sourceLabel: "HubSpot note",
    sender: "Sales rep: Eko",
    company: "Konglomerat Maju",
    date: "Feb 21, 09:00",
    preview: "Note: IT team blocked onboarding — SSO required by policy...",
    full: "Enterprise deal blocked at IT approval stage. IT security team requires SAML SSO as a minimum requirement before they allow any SaaS onboarding. Deal value: IDR 180M ARR. Need product response.",
    signals: ["sso-request"],
    status: "processed" as const,
  },
]

// ─── Signals ──────────────────────────────────────────────────────────────────
export const demoSignals = [
  {
    id: "payroll-sync-gap",
    title: "Payroll sync gap",
    priority: "critical" as const,
    mentions: 18,
    trend: "+6 vs last week",
    category: "Integration",
    sources: ["whatsapp", "zoom", "hubspot"],
    salesSummary: "They want better third-party integrations",
    headline:
      "38% of blocked deals cite missing Gadjian/Talenta sync as a hard blocker — not a nice-to-have.",
    quotes: [
      {
        id: "q1",
        source: "whatsapp",
        sender: "Prospect — PT Karya Maju (300 employees)",
        date: "Feb 18",
        raw: "Kami suka UI-nya tapi tim finance kami tidak mau input data dua kali ke dua sistem. Sampai ada integrasi dengan Gadjian, kami belum bisa pindah.",
        translated:
          "We love your UI but our finance team refuses to double-enter data into two systems. Until you integrate with Gadjian, we can't switch.",
      },
      {
        id: "q2",
        source: "zoom",
        sender: "Prospect — Teknologi Hijau (180 employees)",
        date: "Feb 18",
        raw: "Kalau ada konektor Talenta, saya tanda tangan hari ini.",
        translated: "If you had a Talenta connector I'd sign today.",
      },
      {
        id: "q3",
        source: "hubspot",
        sender: "Prospect — Mitra Solusi (500 employees)",
        date: "Feb 20",
        raw: "Demo-nya bagus tapi kami perlu bicara dulu sama vendor payroll kami. Ini blocker buat kami.",
        translated:
          "The demo was great but we need to talk to our payroll vendor first. This is a blocker for us.",
      },
      {
        id: "q4",
        source: "whatsapp",
        sender: "Prospect — Cahaya Digital (220 employees)",
        date: "Feb 21",
        raw: "Tim payroll kami pakai Gadjian dan mereka tidak akan ganti. Jadi ini mandatory buat kami.",
        translated:
          "Our payroll team uses Gadjian and they won't change. So this is mandatory for us.",
      },
    ],
    competitors: ["AceHR", "Workday SEA", "Bamboo HR"],
    ticketStatus: "created" as const,
    ticketId: "ENG-2041",
    suggestedTicket: {
      title: "Build Gadjian API integration (READ: salary + headcount sync)",
      priority: "P0",
      estimate: "2 sprints",
      description:
        "Implement OAuth-based read-only sync with Gadjian and Talenta APIs. Minimum scope: employee headcount, salary grades, org structure. This unblocks 6 active deals totalling ~IDR 420M ARR.",
      labels: ["integration", "P0", "revenue-critical"],
    },
  },
  {
    id: "mobile-approval-friction",
    title: "Mobile approval friction",
    priority: "critical" as const,
    mentions: 14,
    trend: "+4 vs last week",
    category: "UX / Mobile",
    sources: ["whatsapp", "hubspot"],
    salesSummary: "They want mobile improvements",
    headline:
      "Managers are approving everything blindly on mobile just to clear the queue. Rubber-stamping is not the outcome.",
    quotes: [
      {
        id: "q1",
        source: "whatsapp",
        sender: "Customer — PT Bangun Bersama (onboarded Jan 2026)",
        date: "Feb 17",
        raw: "Manajer ops saya approve dari HP tapi selalu komplain kelamaan. Akhirnya dia approve semua tanpa dibaca biar cepat selesai.",
        translated:
          "My operations manager approves from his phone but always complains it takes too long. He ends up approving everything without reading just to clear it.",
      },
      {
        id: "q2",
        source: "hubspot",
        sender: "Customer — Logistik Nusantara (onboarded Dec 2025)",
        date: "Feb 19",
        raw: "Aplikasi mobile crash kalau ada lebih dari 5 permintaan pending. Ini memperlambat seluruh approval chain kami.",
        translated:
          "The mobile app crashes when there are more than 5 pending requests. This slows our entire approval chain.",
      },
      {
        id: "q3",
        source: "whatsapp",
        sender: "Prospect — Griya Properti (trial)",
        date: "Feb 20",
        raw: "Bisa tombol approve-nya diperbesar? Atasan saya sering salah tap di HP.",
        translated: "Can you make the approve button bigger? My boss keeps missing the tap on mobile.",
      },
    ],
    competitors: ["Keka HR", "Darwinbox"],
    ticketStatus: "created" as const,
    ticketId: "ENG-2042",
    suggestedTicket: {
      title: "Redesign mobile approval: 2-tap flow + fix crash on >5 pending items",
      priority: "P0",
      estimate: "1 sprint",
      description:
        "Reduce approval flow from 5 steps to 2 (swipe or single tap with confirmation). Fix crash triggered by >5 simultaneous pending items. Add haptic confirmation. Target: approval completion rate from 67% to >90%.",
      labels: ["mobile", "UX", "bug", "P0"],
    },
  },
  {
    id: "bulk-import-docs",
    title: "Bulk import documentation missing",
    priority: "medium" as const,
    mentions: 9,
    trend: "new",
    category: "Onboarding",
    sources: ["whatsapp"],
    salesSummary: "Onboarding is complex",
    headline:
      "New customers are calling CS to complete basic onboarding. Every assisted import costs ~2hrs CS time.",
    quotes: [
      {
        id: "q1",
        source: "whatsapp",
        sender: "Customer — Sejahtera Group (onboarded Feb 2026)",
        date: "Feb 18",
        raw: "Kami coba upload 200 karyawan dari sistem lama tapi template Excel-nya tidak ada instruksi. Akhirnya kami telepon support.",
        translated:
          "We tried uploading 200 employees from our old system but the Excel template has no instructions. We ended up calling support.",
      },
      {
        id: "q2",
        source: "whatsapp",
        sender: "Customer — Optima Konsultan (onboarded Feb 2026)",
        date: "Feb 20",
        raw: "Template import ada kolom yang kami tidak mengerti dan tidak ada tooltip atau contoh file-nya.",
        translated:
          "The import template has columns we don't recognize and there's no tooltip or example file.",
      },
    ],
    competitors: [],
    ticketStatus: "pending" as const,
    ticketId: null,
    suggestedTicket: {
      title: "Add bulk import guide: annotated template + step-by-step walkthrough",
      priority: "P1",
      estimate: "3 days",
      description:
        "Create annotated Excel template with example data, required vs optional columns clearly marked. Add in-app walkthrough triggered on first import attempt. Estimated CS savings: 18hrs/month.",
      labels: ["onboarding", "docs", "P1"],
    },
  },
  {
    id: "report-date-range",
    title: "Report export limited to 90 days",
    priority: "low" as const,
    mentions: 7,
    trend: "stable",
    category: "Reporting",
    sources: ["whatsapp"],
    salesSummary: "They need better reporting",
    headline:
      "Finance teams exporting data monthly for annual audits are manually stitching 4 separate exports.",
    quotes: [
      {
        id: "q1",
        source: "whatsapp",
        sender: "Customer — Aman Logistik",
        date: "Feb 19",
        raw: "Saya harus export laporan 4 kali untuk dapat data satu tahun penuh. Bisa langsung pilih range tanggal sendiri?",
        translated:
          "I have to export 4 separate reports to get a full year of data. Can I just pick a custom date range?",
      },
    ],
    competitors: [],
    ticketStatus: "pending" as const,
    ticketId: null,
    suggestedTicket: {
      title: "Extend report export to custom date range (up to 2 years)",
      priority: "P2",
      estimate: "1 day",
      description:
        "Replace fixed 90-day window with custom date picker. Cap at 2 years to prevent timeout issues. Add async export + email delivery for large ranges.",
      labels: ["reporting", "P2"],
    },
  },
  {
    id: "sso-request",
    title: "SSO / SAML request",
    priority: "low" as const,
    mentions: 6,
    trend: "+2 vs last week",
    category: "Enterprise",
    sources: ["hubspot", "zoom"],
    salesSummary: "Some bigger companies need enterprise features",
    headline:
      "Every enterprise prospect > 1000 employees asks about SSO. IT departments won't approve onboarding without it.",
    quotes: [
      {
        id: "q1",
        source: "hubspot",
        sender: "Prospect — Konglomerat Maju (1200 employees)",
        date: "Feb 21",
        raw: "IT kami tidak akan izinkan onboarding tanpa SSO. Ini kebijakan perusahaan.",
        translated: "Our IT team won't allow onboarding without SSO. It's company policy.",
      },
    ],
    competitors: ["SAP SuccessFactors", "Workday"],
    ticketStatus: "pending" as const,
    ticketId: null,
    suggestedTicket: {
      title: "Add Google Workspace SSO (Phase 1)",
      priority: "P2",
      estimate: "1 sprint",
      description:
        "Implement SAML 2.0 with Google Workspace as first provider. Unlocks enterprise segment currently blocked at IT approval stage.",
      labels: ["enterprise", "security", "P2"],
    },
  },
]

export type Signal = (typeof demoSignals)[0]
export type SignalPriority = "critical" | "medium" | "low"
export type IntegrationStatus = "connected" | "available"
